version: '3'

networks:
  translatorapi-dev:
    driver: bridge

services:
  mvc:
    image: mvc:latest
    depends_on: 
      - "api"
    build:
      context: ../P2Translator
      dockerfile: docker-client
    expose:
      - "6000"
    ports:
      - "6000:6000"
    volumes:
      - ./P2Translator.Client:/usr/src/app/


  api:
    image: api:latest
    depends_on: 
      - "postgres_image"
    build: 
      context: ../P2Translator
      dockerfile: docker-api
    volumes: 
      - ./P2Translator.WebApi:/usr/src/app
    expose: 
      - "5000"
    ports:
      - "5000:80"
    environment: 
      DB_CONNECTION_STRING: "host:postgres_image;port:5432;database:postgres;username:postgres;password:postgres"
    networks: 
      - translatorapi-dev

  postgres_image:
    image: postgres:alpine
    ports: 
      - "5432"
    restart: always
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks: 
      - translatorapi-dev