version: '3.4'

networks:
  translatorapi-dev:
    driver: bridge

services:
  mvc:
    image: revaturep2translator/p2translator:mvc
    # build:
    #   context: .
    #   dockerfile: P2Translator.Client/dockerfile
    volumes:
      - MVC:/usr/local/src/app/
    expose:
      - "5000"
    ports:
      - "5000:80"
    networks:
      - translatorapi-dev


  api:
    image: revaturep2translator/p2translator:api
    depends_on: 
      - "postgres_image"
    # build: 
    #   context: .
    #   dockerfile: P2Translator.WebApi/dockerfile
    volumes: 
      - WebApi:/usr/api/src/app
    expose:
      - "5050"
    ports:
      - "5050:80"
    environment: 
      - DB_CONNECTION_STRING="server=postgres_image;port=5432;database=postgres;username=postgres;password=postgres"
    networks: 
      - translatorapi-dev

  postgres_image:
    image: postgres:alpine
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks: 
      - translatorapi-dev